# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factorfiction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
