# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factorfiction', '0002_auto_20170310_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
