# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factorfiction', '0003_auto_20170320_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
