# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factorfiction', '0012_auto_20170323_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
