# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factorfiction', '0016_auto_20170323_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images')),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(default='', max_length=128)),
                ('bio', models.CharField(default='', max_length=1500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
